name: test

on: [push, pull_request]

jobs:
  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    container:
      image: node:12
    steps:
      - uses: actions/checkout@v1
      - name: Run unit tests
        run: |
          yarn install
          yarn test --ci --group=unit --color
  # integration-test:
  #   name: Run integration tests
  #   runs-on: ubuntu-latest
  #   container:
  #     image: zeptometer/node-diff-pdf:latest
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Run integration tests
  #       run: |
  #         yarn install
  #         yarn test --ci --group=integration